import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import { compileBeats, type Beat } from "./beats";
import {
  Curriculum,
  CurriculumSchema,
  CurriculumEntry,
  ModuleMeta,
  ModuleMetaSchema,
  Exercise,
  ExercisesFileSchema,
  LessonFrontmatter,
  LessonFrontmatterSchema,
  ProgressStore,
} from "./schema";

export const ROOT = process.cwd();
export const CONTENT_DIR = path.join(ROOT, "content");
export const MODULES_DIR = path.join(CONTENT_DIR, "modules");

// ---------- Build-time compiled MDX (REQ-CP-01) ----------
//
// MDX is compiled by Velite at BUILD time (velite.config.ts -> `.velite/lessons.json`).
// Nothing in this module compiles MDX; the request path only READS already-compiled
// output. `next-mdx-remote` is gone.
//
// WHY fs INSTEAD OF `import lessons from "../../.velite"`:
//   1. `.velite` is a dot-directory, and TypeScript's wildcard include patterns
//      (`**/*.ts` in tsconfig.json) never match dot-prefixed directories. A static
//      import would therefore make `npx tsc --noEmit` and `npm run lint` HARD-FAIL on
//      any checkout where the generated output is absent — and it is absent by design,
//      being gitignored and regenerated by the build.
//   2. Every other loader in this file already reads content from disk relative to
//      `process.cwd()`, so this stays idiomatic with the rest of the module.

export const VELITE_DIR = path.join(ROOT, ".velite");
export const COMPILED_LESSONS_PATH = path.join(VELITE_DIR, "lessons.json");

/**
 * One lesson as emitted by Velite. `code` is a compiled MDX **function body** (Velite's
 * default `outputFormat: 'function-body'`), evaluated by the renderer — never compiled
 * in the request path.
 */
export type CompiledLesson = {
  id: string;
  title: string;
  minutes: number;
  objectives: string[];
  filePath: string;
  code: string;
  moduleId: string;
  lessonId: string;
  key: string;
};

/**
 * Process-lifetime cache of the compiled bundle.
 *
 * Cached in production only. Under `npm run content:watch` (`velite dev`) the compiled
 * output is rewritten while the server keeps running, so caching in development would
 * pin the first-read version and serve stale prose for the rest of the session — the
 * sharpest edge of Velite's two-process DX (OPEN-QUESTIONS #10).
 */
let compiledLessonsCache: CompiledLesson[] | undefined;
const shouldCacheCompiledLessons = process.env.NODE_ENV === "production";

/** Discard the cached bundle. Exposed for tests and for post-recompile invalidation. */
export function clearCompiledLessonsCache(): void {
  compiledLessonsCache = undefined;
}

/**
 * All lessons compiled by Velite, or `undefined` when the bundle has not been built.
 *
 * Returning `undefined` rather than throwing is deliberate: `getExercise()` and
 * `allExercisesPassed()` reach `loadLesson()` from six API routes and from progress
 * computation, and NONE of them need compiled MDX. A hard throw here would couple quiz
 * submission, playground scoring and challenge verification to an artifact they never
 * read.
 */
function readCompiledLessons(): CompiledLesson[] | undefined {
  if (compiledLessonsCache) return compiledLessonsCache;
  if (!fs.existsSync(COMPILED_LESSONS_PATH)) return undefined;
  const raw: unknown = JSON.parse(
    fs.readFileSync(COMPILED_LESSONS_PATH, "utf-8")
  );
  if (!Array.isArray(raw)) {
    throw new Error(
      `${COMPILED_LESSONS_PATH} is malformed: expected a JSON array of compiled ` +
        `lessons. Delete \`.velite/\` and re-run \`npm run content:build\`.`
    );
  }
  const lessons = raw as CompiledLesson[];
  if (shouldCacheCompiledLessons) compiledLessonsCache = lessons;
  return lessons;
}

/**
 * All lessons compiled by Velite. Throws with a remediation hint when the build-time
 * step has not run — for callers that genuinely cannot proceed without it.
 */
export function loadCompiledLessons(): CompiledLesson[] {
  const lessons = readCompiledLessons();
  if (!lessons) {
    throw new Error(
      `Compiled lesson content is missing at ${COMPILED_LESSONS_PATH}. MDX is compiled ` +
        `at build time by Velite — run \`npm run content:build\` (or \`npm run build\`, ` +
        `which chains it) before serving.`
    );
  }
  return lessons;
}

/**
 * The compiled lesson for a module/lesson pair. `undefined` both when the lesson is not
 * in the bundle and when the bundle itself has not been built, so callers degrade
 * gracefully instead of crashing unrelated request paths.
 */
export function getCompiledLesson(
  moduleId: string,
  lessonId: string
): CompiledLesson | undefined {
  const lessons = readCompiledLessons();
  if (!lessons) return undefined;
  const key = lessonKey(moduleId, lessonId);
  return lessons.find((l) => l.key === key);
}

export function loadCurriculum(): Curriculum {
  const raw = JSON.parse(
    fs.readFileSync(path.join(CONTENT_DIR, "curriculum.json"), "utf-8")
  );
  return CurriculumSchema.parse(raw);
}

export function getModuleEntry(moduleId: string): CurriculumEntry | undefined {
  return loadCurriculum().modules.find((m) => m.id === moduleId);
}

export function loadModuleMeta(moduleId: string): ModuleMeta {
  const raw = JSON.parse(
    fs.readFileSync(path.join(MODULES_DIR, moduleId, "module.json"), "utf-8")
  );
  return ModuleMetaSchema.parse(raw);
}

/**
 * Load one lesson.
 *
 * `frontmatter` is still parsed with `LessonFrontmatterSchema` — the steward-owned
 * authoring contract in `src/lib/schema.ts` — so authored extension fields survive;
 * Velite's own collection schema drops unknown keys and is NOT a substitute for it.
 * Reading YAML frontmatter is not MDX compilation, so `gray-matter` legitimately stays.
 *
 * `mdx` is the raw MDX body. It is retained (the field name and type are unchanged, so
 * the existing `src/app/learn/**` call site keeps compiling) but it is NO LONGER what
 * gets rendered.
 * `code` is the build-time-compiled MDX from Velite and IS what gets rendered. It is
 * `undefined` only when the Velite step has not run; the renderer surfaces that as a
 * remediation callout rather than a crash, and the exercise-only callers
 * (`getExercise`, `allExercisesPassed`) simply ignore it.
 */
export function loadLesson(
  moduleId: string,
  lessonId: string
): {
  frontmatter: LessonFrontmatter;
  mdx: string;
  code: string | undefined;
  exercises: Exercise[];
} {
  const dir = path.join(MODULES_DIR, moduleId, "lessons", lessonId);
  const source = fs.readFileSync(path.join(dir, "lesson.mdx"), "utf-8");
  const { data, content } = matter(source);
  const frontmatter = LessonFrontmatterSchema.parse(data);
  const exercisesPath = path.join(dir, "exercises.json");
  const exercises = fs.existsSync(exercisesPath)
    ? ExercisesFileSchema.parse(
        JSON.parse(fs.readFileSync(exercisesPath, "utf-8"))
      )
    : [];
  const code = getCompiledLesson(moduleId, lessonId)?.code;
  return { frontmatter, mdx: content, code, exercises };
}

export function getExercise(
  moduleId: string,
  lessonId: string,
  exerciseId: string
): Exercise | undefined {
  return loadLesson(moduleId, lessonId).exercises.find(
    (e) => e.id === exerciseId
  );
}

// ---------- Beat compilation (REQ-CP-02) ----------
//
// The beat compiler itself is `src/lib/beats.ts` — pure, I/O-free, so its determinism
// (invariant S2) is a property of the code rather than a thing tests must chase. This
// section is only the I/O seam: read authored source, hand it to `compileBeats`.
//
// WHY A SEPARATE ENTRY POINT INSTEAD OF A FIELD ON `loadLesson()`:
// `loadLesson()` is reached from six API routes and from progress computation, none of
// which read beats — the same argument the compiled-bundle readers above make for
// degrading rather than throwing. Compiling beats inside `loadLesson()` would put a
// build-failure throw (a duplicate beat key, an unresolvable anchor) in the path of quiz
// submission and challenge verification. Beat consumers ask for beats explicitly.
//
// The re-export below is REQ-CP-02's "current state" note — `src/lib/content.ts` "gains
// the beat-compile step" — satisfied without making this file the definition site.

export type {
  Beat,
  BeatType,
  CompletionPredicate,
  BeatSourceExercise,
} from "./beats";
export {
  compileBeats,
  assertValidBeats,
  slugifyHeading,
  BeatCompileError,
  COMPLETION_BY_BEAT_TYPE,
  PERSISTENT_BEAT_TYPES,
  EXERCISE_BEAT_ID_PREFIX,
  PROSE_BEAT_ID_PREFIX,
  INTRO_BEAT_ID,
} from "./beats";

/**
 * The ordered beat array for one lesson (REQ-CP-02 scenario 1).
 *
 * Compiled from the AUTHORED MDX body plus `exercises.json`, never from Velite's compiled
 * `code` (which is a JS function body — see `compileBeats`). Throws `BeatCompileError`,
 * i.e. fails the build, when the lesson violates a compiler invariant.
 */
export function getLessonBeats(moduleId: string, lessonId: string): Beat[] {
  const { mdx, exercises } = loadLesson(moduleId, lessonId);
  return compileBeats(mdx, exercises, lessonKey(moduleId, lessonId));
}

/**
 * Every built lesson's beat array, keyed by `lessonKey()` — the whole-bundle view
 * REQ-CP-02 scenario 1 quantifies over ("given ANY built lesson"). Modules whose
 * curriculum `status` is not `"built"` have no lesson files on disk yet and are skipped.
 */
export function compileAllLessonBeats(): Record<string, Beat[]> {
  const out: Record<string, Beat[]> = {};
  for (const entry of loadCurriculum().modules) {
    if (entry.status !== "built") continue;
    for (const lesson of loadModuleMeta(entry.id).lessons) {
      out[lessonKey(entry.id, lesson.id)] = getLessonBeats(entry.id, lesson.id);
    }
  }
  return out;
}

// ---------- Gating ----------

export function lessonKey(moduleId: string, lessonId: string): string {
  return `${moduleId}/${lessonId}`;
}

export function isLessonComplete(
  progress: ProgressStore,
  moduleId: string,
  lessonId: string
): boolean {
  return Boolean(progress.lessons[lessonKey(moduleId, lessonId)]?.completedAt);
}

export function isModuleComplete(
  progress: ProgressStore,
  moduleId: string
): boolean {
  const entry = getModuleEntry(moduleId);
  if (!entry || entry.status !== "built") return false;
  const meta = loadModuleMeta(moduleId);
  return meta.lessons.every((l) => isLessonComplete(progress, moduleId, l.id));
}

export function isModuleUnlocked(
  progress: ProgressStore,
  moduleId: string
): boolean {
  const entry = getModuleEntry(moduleId);
  if (!entry) return false;
  return entry.requires.every((req) => isModuleComplete(progress, req));
}

/** Lessons unlock sequentially within a module. */
export function isLessonUnlocked(
  progress: ProgressStore,
  moduleId: string,
  lessonId: string
): boolean {
  if (!isModuleUnlocked(progress, moduleId)) return false;
  const meta = loadModuleMeta(moduleId);
  const idx = meta.lessons.findIndex((l) => l.id === lessonId);
  if (idx < 0) return false;
  return meta.lessons
    .slice(0, idx)
    .every((l) => isLessonComplete(progress, moduleId, l.id));
}

/**
 * Check whether every REQUIRED exercise in a lesson is passed; if so the lesson is complete.
 *
 * `playground` exercises are graded by the LLM judge (`src/lib/bedrock.ts`), which currently
 * runs offline (no Bedrock/Anthropic backend configured) and always returns an unpassable
 * result. Excluding them from the completion gate keeps quiz-graded lessons progressable
 * while the judge is offline; re-include them once a live model backend is wired up.
 */
export function allExercisesPassed(
  progress: ProgressStore,
  moduleId: string,
  lessonId: string
): boolean {
  const { exercises } = loadLesson(moduleId, lessonId);
  const required = exercises.filter((ex) => ex.type !== "playground");
  const lp = progress.lessons[lessonKey(moduleId, lessonId)];
  if (!lp) return required.length === 0;
  return required.every((ex) => lp.exercises[ex.id]?.status === "passed");
}

export function moduleCompletionPercent(
  progress: ProgressStore,
  moduleId: string
): number {
  const entry = getModuleEntry(moduleId);
  if (!entry || entry.status !== "built") return 0;
  const meta = loadModuleMeta(moduleId);
  if (meta.lessons.length === 0) return 0;
  const done = meta.lessons.filter((l) =>
    isLessonComplete(progress, moduleId, l.id)
  ).length;
  return Math.round((done / meta.lessons.length) * 100);
}
